### PR TITLE
Use .rspec rather than spec.opts

### PR DESCRIPTION
**Pull request by juniorsysadmin**
spec.opts is deprecated in RSpec 2

### CODE REVIEW

**Comment by DavidS** [comment]
:+1:

**Comment by alexjfisher** [comment]
Are the options in spec.opts (the file being renamed) actually compatible with rspec 3?

**Comment by DavidS** [comment]
Interesting question. I admit, I hadn't checked.

**Comment by alexjfisher** [comment]
--loadby wasn't even valid in rspec 2?
http://makandracards.com/makandra/1282-order-in-which-rspec-processes-rb-files

Even if this PR is dodgy, I still think a suitable .rspec should replace the existing (and presumably unused) spec.opts.  Lots of module authors use the puppetlabs modules as examples.

**Comment by juniorsysadmin** [comment]
Are --format s and mtime invalid as well?

**Comment by DavidS** [comment]
Closing in favour of #36. Thanks for catching that, @juniorsysadmin and @alexjfisher .

**Pull request closed without merging**
