### PR TITLE
FM-5711 add blacksmith to rake(not used on win)

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
supersedes #101

**Comment by tphoney** [comment]
@glennsarti @ferventcoder after the merge of @hunner PR it was easier to create a new PR, however i found an alternate / existing way of guarding the rakefile. https://github.com/puppetlabs/puppetlabs-dsc/blob/master/Rakefile#L3-L4  what is your preference ?

**Comment by tphoney** [comment]
@glennsarti @ferventcoder can you have a look ? any preference for implementation mentioned above.

**Comment by glennsarti** [comment]
Not sure it's worth guarding it for Windows.  And we won't then need to updated the rake file once puppet-blacksmith is used in Windows.

**Comment by ferventcoder** [comment]
I like the one in DSC - it adds it if it is there, otherwise it just says no. 👍

**Comment by tphoney** [comment]
@ferventcoder @glennsarti  made the changes as per your request. here is the rake output for dism 
`➜  puppetlabs-dism git:(master) ✗ bundle exec rake --tasks
rake beaker                                  # Run beaker acceptance tests
rake beaker:sets                             # List available beaker nodesets
rake beaker:ssh[set,node]                    # Try to use vagrant to login to the Beaker node
rake build                                   # Build puppet module package
rake check:dot_underscore                    # Fails if any ._ files are present in directory
rake check:git_ignore                        # Fails if directories contain the files specified in .gitignore
rake check:symlinks                          # Fails if symlinks are present in directory
rake check:test_file                         # Fails if .pp files present in tests folder
rake clean                                   # Clean a built module package
rake compute_dev_version                     # Print development version of module
rake help                                    # Display the list of available rake tasks
rake lint                                    # Run puppet-lint
rake metadata_lint                           # Run metadata-json-lint
rake module:bump                             # Bump module version to the next patch
rake module:bump:full                        # Bump module version to the next FULL version
rake module:bump:major                       # Bump module version to the next MAJOR version
rake module:bump:minor                       # Bump module version to the next MINOR version`

and here for acl

> puppetlabs-acl git:(master) ✗ bundle exec rake --tasks
rake beaker                   # Run beaker acceptance tests
rake beaker:sets              # List available beaker nodesets
rake beaker:ssh[set,node]     # Try to use vagrant to login to the Beaker node
rake beaker:test[hosts,type]  # Run Beaker Acceptance
rake beaker:test:git[hosts]   # Run Beaker Git tests
rake beaker:test:pe[hosts]    # Run Beaker PE tests
rake beaker_git[hosts,tests]  # Run Beaker Git Tests
rake beaker_pe[hosts,tests]   # Run Beaker PE Tests
rake build                    # Build puppet module package
rake check:dot_underscore     # Fails if any ._ files are present in directory
rake check:git_ignore         # Fails if directories contain the files specified in .gitignore
rake check:symlinks           # Fails if symlinks are present in directory
rake check:test_file          # Fails if .pp files present in tests folder
rake clean                    # Clean a built module package
rake compute_dev_version      # Print development version of module
rake coverage                 # Generate code coverage
rake help                     # Display the list of available rake tasks
rake lint                     # Run puppet-lint
rake metadata_lint            # Run metadata-json-lint
rake parallel_spec            # Parallel spec tests
rake release_checks           # Runs all necessary checks on a module in preparation for a re

**Comment by tphoney** [comment]
@ferventcoder @glennsarti can you have a look please

**Comment by glennsarti** [comment]
Looks fine by me... 👍 for merge

**Comment by ferventcoder** [comment]
Also a 👍 

Man I'm behind on notifications.

**Pull request merged**
