### PR TITLE
Mergeback Windows

### PR DESCRIPTION
**Pull request by hunner**
And the schism has been peacefully resolved.

### CODE REVIEW

**Comment by DavidS** [comment]
:tada:

**Comment by DavidS** [comment]
I've checked this locally and this does what you wanted it too. Github is showing you all the commits going in, not the actual merge delta.

**Comment by hunner** [comment]
Chocolatey failure is probably related to line endings https://github.com/puppetlabs/modulesync_configs/pull/60#issuecomment-212132608

**Comment by DavidS** [comment]
Can we fix this there?

**Comment by ferventcoder** [comment]
🎆

**Comment by michaeltlombardi** [comment]
Can we blow this up since we're not modsyncing from a separate branch anymore?

**Pull request closed without merging**
