### PR TITLE
(maint) rename all files to *.erb to avoid confusion

### PR DESCRIPTION
**Pull request by DavidS**
Especially .gitattributes is very annoying, but all can benefit from correct syntax highlighting.

### CODE REVIEW

**Comment by DavidS** [comment]
This requires https://github.com/voxpupuli/modulesync/pull/113 to work.

**Comment by DavidS** [comment]
modulesync 0.8.0 no has the required fixes, and this is green.

**Comment by tphoney** [comment]
@DavidS is this still important ?

**Comment by pmcmaw** [comment]
Hey @DavidS 
I can see https://github.com/voxpupuli/modulesync/pull/113 is closed which this relies on.
Do you have any objections to me closing this? :-)

**Comment by DavidS** [comment]
https://github.com/puppetlabs/modulesync_configs/pull/164 supersedes this.

**Comment by pmcmaw** [comment]
Thank you @DavidS :-)

**Pull request closed without merging**
