### PR TITLE
fix rubocop / ruby 2 dependancy

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by DavidS** [comment]
Who is pulling in rubocop, and why can't we fix it there?

**Comment by tphoney** [comment]
Fair point, i fixed this in stdlib. from your reaction early you mentioned that it was spread throughout supported modules. I probably misheard

**Comment by DavidS** [comment]
Sorry for the confusion, I tried to refer to fixing the issue at its root. I've checked now and rubocop is a dependency of puppetlabs_spec_helper, and we cannot add ruby-version-aware dependencies on the gem, so this workaround is the best we can do

**Comment by bastelfreak** [comment]
I did a different approach in voxpupuli. We run rubocop only on ruby2.3.1. We modified the Gemfile to only install rubocop/rubocop-rspec on ruby2.3.1. 
[config_defaults.yml](https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml#L45)
[Rakefile](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/Rakefile#L6-L13)
[Gemfile](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/Gemfile#L47)

**Comment by DavidS** [comment]
@bastelfreak have you had any issues with rubocop's suggestions/fixes on older rubies?

**Comment by bastelfreak** [comment]
We dropped Ruby1.8.7 support a while ago because we enabled the new hashrocket syntax. We define a [TargetRubyVersion](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.rubocop.yml#L3) in our rubocop config which currently tests our codebase against ruby193 syntax. But we execute rubocop on ruby231. (I hope that doesn't sound too confusing.)

So everything rubocop produces is still ruby193 conform.

**Comment by DavidS** [comment]
+:100:

**Comment by DavidS** [comment]
rubocop is now listed in config_defaults.

**Pull request closed without merging**
